# Generated by Django 5.2.4 on 2025-07-05 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('regime_tributario', models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real')], default='SIMPLES', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_cofins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_iss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao_produtos', models.TextField(blank=True)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='nfe_xmls/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='auditoria.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'numero', 'data_emissao')},
            },
        ),
    ]
