# Generated by Django 5.2.4 on 2025-07-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DIRF', 'DIRF'), ('DMRI', 'DMRI'), ('DAS', 'DAS'), ('NFE', 'Nota Fiscal Eletrônica (NF-e)'), ('NFCE', 'Nota Fiscal de Consumidor Eletrônica (NFC-e)'), ('NFSE', 'Nota Fiscal de Serviço Eletrônica (NFS-e)'), ('CTE', 'Conhecimento de Transporte Eletrônico (CT-e)'), ('LIVRO_FISCAL', 'Livro Fiscal'), ('BALANCETE', 'Balancete'), ('SPED_ECF', 'SPED ECF'), ('SPED_ECD', 'SPED ECD'), ('SPED_EFD_ICMS_IPI', 'SPED EFD-ICMS/IPI'), ('SPED_EFD_CONTRIBUICOES', 'SPED EFD-Contribuições'), ('DCTF', 'DCTF'), ('DARF', 'DARF'), ('GPS', 'GPS'), ('GRF', 'GRF'), ('DEFIS', 'DEFIS'), ('MDFE', 'Manifesto de Documentos Fiscais Eletrônicos (MDF-e)')], max_length=50)),
                ('mes', models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ano', models.IntegerField()),
                ('arquivo', models.FileField(upload_to='documentos_fiscais/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscais', to='auditoria.empresa')),
            ],
            options={
                'ordering': ['ano', 'mes'],
                'unique_together': {('empresa', 'tipo_documento', 'mes', 'ano')},
            },
        ),
    ]
