# Generated by Django 5.2.4 on 2025-07-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_documentofiscal'),
    ]

    operations = [
    ]
