# Generated by Django 5.2.4 on 2025-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_empresa_resultado_auditoria_empresa_resultado_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtualizacaoTIPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(help_text='Total de registros atualizados')),
                ('registros_novos', models.IntegerField(help_text='Registros novos adicionados')),
                ('registros_alterados', models.IntegerField(help_text='Registros existentes alterados')),
                ('fonte_dados', models.CharField(help_text='URL ou fonte dos dados', max_length=255)),
                ('usuario', models.CharField(help_text='Usuário que executou a atualização', max_length=100)),
                ('sucesso', models.BooleanField(default=True)),
                ('log_detalhes', models.TextField(blank=True, help_text='Log detalhado da atualização')),
            ],
            options={
                'verbose_name': 'Histórico de Atualização TIPI',
                'verbose_name_plural': 'Históricos de Atualizações TIPI',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='TabelaTIPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ncm', models.CharField(help_text='Código NCM do produto', max_length=20, unique=True)),
                ('descricao', models.TextField(help_text='Descrição do produto conforme TIPI')),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, help_text='Alíquota do IPI em %', max_digits=5)),
                ('observacoes', models.TextField(blank=True, help_text='Observações e exceções')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('decreto_origem', models.CharField(blank=True, help_text='Decreto que estabeleceu/alterou a alíquota', max_length=100)),
                ('vigencia_inicio', models.DateField(blank=True, help_text='Data de início da vigência', null=True)),
                ('vigencia_fim', models.DateField(blank=True, help_text='Data de fim da vigência (se aplicável)', null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se o código está ativo')),
            ],
            options={
                'verbose_name': 'Tabela TIPI',
                'verbose_name_plural': 'Tabelas TIPI',
                'ordering': ['codigo_ncm'],
            },
        ),
    ]
