# Generated by Django 5.2.4 on 2025-07-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_historicoatualizacaotipi_tabelatipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da legislação', max_length=500)),
                ('numero', models.CharField(help_text='Número da legislação', max_length=50)),
                ('ano', models.IntegerField(help_text='Ano da legislação')),
                ('tipo', models.CharField(choices=[('LEI', 'Lei'), ('DECRETO', 'Decreto'), ('INSTRUCAO_NORMATIVA', 'Instrução Normativa'), ('PORTARIA', 'Portaria'), ('RESOLUCAO', 'Resolução'), ('MEDIDA_PROVISORIA', 'Medida Provisória'), ('CONSTITUICAO', 'Constituição'), ('CODIGO', 'Código'), ('CONSOLIDACAO', 'Consolidação'), ('ATO_DECLARATORIO', 'Ato Declaratório'), ('SOLUCAO_CONSULTA', 'Solução de Consulta'), ('PARECER', 'Parecer')], help_text='Tipo de legislação', max_length=30)),
                ('area', models.CharField(choices=[('TRIBUTARIO', 'Tributário'), ('FISCAL', 'Fiscal'), ('TRABALHISTA', 'Trabalhista'), ('PREVIDENCIARIO', 'Previdenciário'), ('COMERCIAL', 'Comercial'), ('CIVIL', 'Civil'), ('PENAL', 'Penal'), ('ADMINISTRATIVO', 'Administrativo'), ('CONSTITUCIONAL', 'Constitucional'), ('AMBIENTAL', 'Ambiental')], help_text='Área de aplicação', max_length=30)),
                ('orgao', models.CharField(choices=[('RECEITA_FEDERAL', 'Receita Federal do Brasil'), ('CONGRESSO_NACIONAL', 'Congresso Nacional'), ('PRESIDENCIA', 'Presidência da República'), ('MINISTERIO_FAZENDA', 'Ministério da Fazenda'), ('MINISTERIO_ECONOMIA', 'Ministério da Economia'), ('MINISTERIO_TRABALHO', 'Ministério do Trabalho'), ('INSS', 'Instituto Nacional do Seguro Social'), ('CONFAZ', 'Conselho Nacional de Política Fazendária'), ('CARF', 'Conselho Administrativo de Recursos Fiscais'), ('STF', 'Supremo Tribunal Federal'), ('STJ', 'Superior Tribunal de Justiça'), ('TST', 'Tribunal Superior do Trabalho'), ('TCU', 'Tribunal de Contas da União'), ('OUTROS', 'Outros')], help_text='Órgão emissor', max_length=30)),
                ('data_publicacao', models.DateField(help_text='Data de publicação')),
                ('data_vigencia', models.DateField(blank=True, help_text='Data de início da vigência', null=True)),
                ('data_revogacao', models.DateField(blank=True, help_text='Data de revogação (se aplicável)', null=True)),
                ('ementa', models.TextField(help_text='Ementa da legislação')),
                ('texto_completo', models.TextField(blank=True, help_text='Texto completo da legislação')),
                ('resumo', models.TextField(blank=True, help_text='Resumo executivo')),
                ('url_oficial', models.URLField(blank=True, help_text='URL oficial da legislação')),
                ('diario_oficial', models.CharField(blank=True, help_text='Referência do Diário Oficial', max_length=200)),
                ('palavras_chave', models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula')),
                ('ativo', models.BooleanField(default=True, help_text='Se a legislação está ativa')),
                ('relevancia', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Crítica')], default=3, help_text='Relevância para o sistema')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('legislacao_relacionada', models.ManyToManyField(blank=True, help_text='Legislações relacionadas', to='auditoria.legislacao')),
            ],
            options={
                'verbose_name': 'Legislação',
                'verbose_name_plural': 'Legislações',
                'ordering': ['-data_publicacao', '-relevancia'],
                'unique_together': {('tipo', 'numero', 'ano', 'orgao')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricoAtualizacaoTIPI',
        ),
    ]
