# Generated by Django 5.2.4 on 2025-07-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_remove_historico_atualizacao_tipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislacao',
            name='esfera',
            field=models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], default='FEDERAL', help_text='Esfera de competência', max_length=20),
        ),
        migrations.AlterField(
            model_name='legislacao',
            name='orgao',
            field=models.CharField(choices=[('RECEITA_FEDERAL', 'Receita Federal do Brasil'), ('CONGRESSO_NACIONAL', 'Congresso Nacional'), ('PRESIDENCIA', 'Presidência da República'), ('MINISTERIO_FAZENDA', 'Ministério da Fazenda'), ('MINISTERIO_ECONOMIA', 'Ministério da Economia'), ('MINISTERIO_TRABALHO', 'Ministério do Trabalho'), ('INSS', 'Instituto Nacional do Seguro Social'), ('CONFAZ', 'Conselho Nacional de Política Fazendária'), ('CARF', 'Conselho Administrativo de Recursos Fiscais'), ('STF', 'Supremo Tribunal Federal'), ('STJ', 'Superior Tribunal de Justiça'), ('TST', 'Tribunal Superior do Trabalho'), ('TCU', 'Tribunal de Contas da União'), ('SENADO_FEDERAL', 'Senado Federal'), ('OUTROS', 'Outros')], help_text='Órgão emissor', max_length=30),
        ),
    ]
