# Generated by Django 5.2.4 on 2025-07-09 21:23

import auditoria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_alter_documentofiscal_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='arquivo',
            field=models.FileField(upload_to='documentos_fiscais/%Y/%m/', validators=[auditoria.models.validate_file_extension, auditoria.models.validate_file_size]),
        ),
    ]
