# Generated by Django 5.2.4 on 2025-07-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0009_alter_documentofiscal_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='atividade_principal',
            field=models.CharField(blank=True, help_text='Atividade principal da empresa', max_length=300),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_principal',
            field=models.CharField(blank=True, help_text='CNAE principal (ex: 6201-5)', max_length=10),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estados_operacao',
            field=models.CharField(blank=True, help_text='Estados onde opera (separados por vírgula)', max_length=500),
        ),
        migrations.AddField(
            model_name='empresa',
            name='exporta',
            field=models.BooleanField(default=False, help_text='Realiza exportações?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='faturamento_anual',
            field=models.CharField(blank=True, choices=[('ATE_360K', 'Até R$ 360.000'), ('360K_4_8M', 'De R$ 360.000 a R$ 4.800.000'), ('4_8M_300M', 'De R$ 4.800.000 a R$ 300.000.000'), ('ACIMA_300M', 'Acima de R$ 300.000.000')], help_text='Faixa de faturamento anual', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='importa',
            field=models.BooleanField(default=False, help_text='Realiza importações?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_funcionarios',
            field=models.CharField(blank=True, choices=[('0_9', '0 a 9 funcionários'), ('10_49', '10 a 49 funcionários'), ('50_99', '50 a 99 funcionários'), ('100_499', '100 a 499 funcionários'), ('500_MAIS', '500 ou mais funcionários')], help_text='Número de funcionários', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observacoes_fiscais',
            field=models.TextField(blank=True, help_text='Observações especiais sobre a situação fiscal da empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='quais_beneficios',
            field=models.TextField(blank=True, help_text='Quais benefícios fiscais possui?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_apuracao',
            field=models.CharField(blank=True, choices=[('MENSAL', 'Apuração Mensal'), ('TRIMESTRAL', 'Apuração Trimestral'), ('ANUAL', 'Apuração Anual')], help_text='Regime de apuração dos tributos', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='setor_atuacao',
            field=models.CharField(blank=True, choices=[('INDUSTRIA', 'Indústria'), ('COMERCIO', 'Comércio'), ('SERVICOS', 'Serviços'), ('CONSTRUCAO', 'Construção Civil'), ('AGRICULTURA', 'Agricultura'), ('TECNOLOGIA', 'Tecnologia'), ('SAUDE', 'Saúde'), ('EDUCACAO', 'Educação'), ('FINANCEIRO', 'Financeiro'), ('TRANSPORTES', 'Transportes'), ('OUTROS', 'Outros')], help_text='Setor principal de atuação', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_beneficios_fiscais',
            field=models.BooleanField(default=False, help_text='Possui benefícios fiscais?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_filiais',
            field=models.BooleanField(default=False, help_text='Possui filiais?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_gastos_ambientais',
            field=models.BooleanField(default=False, help_text='Tem gastos com preservação ambiental?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_gastos_pd',
            field=models.BooleanField(default=False, help_text='Tem gastos com Pesquisa e Desenvolvimento?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tem_gastos_treinamento',
            field=models.BooleanField(default=False, help_text='Tem gastos com treinamento de funcionários?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_pj',
            field=models.BooleanField(default=False, help_text='Contrata Pessoa Jurídica (PJ)?'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_terceirizacao',
            field=models.BooleanField(default=False, help_text='Usa serviços terceirizados?'),
        ),
    ]
