# Generated by Django 5.2.4 on 2025-07-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0011_adicionar_campos_ncm_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP da empresa (formato: XXXXX-XXX)', max_length=9),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade onde está localizada a empresa', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado onde está localizada a empresa', max_length=50),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF do estado (ex: SP, RJ, MG)', max_length=2),
        ),
    ]
