# Generated by Django 5.2.4 on 2025-07-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0012_adicionar_localizacao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislacao',
            name='estado_especifico',
            field=models.CharField(blank=True, help_text='Estado específico para legislações estaduais', max_length=50),
        ),
        migrations.AddField(
            model_name='legislacao',
            name='municipio_especifico',
            field=models.CharField(blank=True, help_text='Município específico para legislações municipais', max_length=100),
        ),
        migrations.AddField(
            model_name='legislacao',
            name='uf_especifica',
            field=models.CharField(blank=True, choices=[('', 'Não especificado'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='UF específica para legislações estaduais (ex: SP, RJ, MG)', max_length=2),
        ),
    ]
