[build]
  command = "./build-universal.sh"
  publish = "staticfiles"

[build.environment]
  DJANGO_SETTINGS_MODULE = "netlify_settings"
  DEBUG = "False"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[redirects]]
  from = "/auditoria/*"
  to = "/auditoria/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/auditoria/"
  status = 200 