[build]
builder = "nixpacks"

[deploy]
startCommand = "./start-railway.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
DJANGO_SETTINGS_MODULE = "railway_settings"
DEBUG = "False"
PYTHONUNBUFFERED = "1"
PORT = "8000" 