[build]
builder = "nixpacks"

[deploy]
startCommand = "./start-railway-minimal.sh"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[variables]
DJANGO_SETTINGS_MODULE = "railway_settings_minimal"
DEBUG = "False"
PYTHONUNBUFFERED = "1" 