services:
  - type: web
    name: fisco-auditoria
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && python manage.py migrate && gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: fisco-db
          property: connectionString
    healthCheckPath: /admin/

databases:
  - name: fisco-db
    databaseName: fisco
    user: fisco_user 